on: push
name: "测试软件在macos下的运行"
jobs:
  testBrew:
    name: 测试dev版本
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: 构建和测试包的homebrew套件
      run: |
        cd tools/build/homebrew
        echo "将套件中的Hash替换为当前Hash $(git rev-parse --verify HEAD)"
        sed -i.bck "s/COMMIT_HASH/$(git rev-parse --verify HEAD)/" Lanraragi.rb
        brew install --force --verbose --build-from-source Lanraragi.rb
        brew test --verbose Lanraragi.rb