on: push
name: "Test Homebrew"
jobs:
  testBrew:
    name: 测试 Homebrew 版
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test bundled homebrew formula
      run: |
        cd tools/build/homebrew
        echo "Replacing commit hash in formula with current hash $(git rev-parse --verify HEAD)"
        sed -i.bck "s/COMMIT_HASH/$(git rev-parse --verify HEAD)/" Lanraragi.rb
        brew install --force --verbose --build-from-source Lanraragi.rb
        brew test --verbose Lanraragi.rb