on: [push, pull_request]
name: "Continuous Integration \U0001F44C\U0001F440"
jobs:
  testSuite:
    name: Run Test Suite and Perl Critic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Docker Build
      run: |
        docker build -t difegue/lanraragi -f ./tools/build/docker/Dockerfile .
    - name: LANraragi Test Suite
      uses: ./.github/action-run-tests
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./lib/* ./script/* ./tools/install.pl